// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w9XW/cOJJ/hdDdwx3QcTue7ODWwD44TmYvmCRjxE72gIxxYEvV3VxLlJakbDeM/u8L",
	"fkmURErqdrttJ36aSYsfxapifbGqfBfFeVbkFKjg0fFdVGCGMxDA1L9wHAPnF/kV0A/v5A+ERsdRgcUy",
	"mkQUZxAdt8ZMIgb/KgmDJDoWrIRJxOMlZFhOFqtCTuCCEbqI1utJhAvyO6zCS9vPm606K0maBBe1Xzdb",
	"k+YJBJc0HzdbkWOazPLb4KL1983WFZAVKRZhaJ0Bm6y8loN5kVMOijfeHB7K/8Q5FUCF4paiSEmMBcnp",
	"9J88p/K3er3/ZDCPjqP/mNYMN9Vf+fQ9YznTeyTAY0YKuUh0HL3FCZIgAhfRehK9OXz98HuelGIJVJhV",
	"EehxcvM3D7/551ygeV7SRO/414ff8TSn85TECr9/2QdNz4FdA7N4XVueU0x1evb1NC/11i0wz76iOGfA",
	"0TxnSCwBmQsSTaJ5zjIsouOIUPHLUTSJMkJJVmbR8euJ5WNCBSxAEfKUARaQnNSCS0k+lhfABNHcHZsx",
	"HkguSAZc4KxA+Rxp6YeEXAWpSXKQA1KCBbwSJINo0r5Sk4gk3eU/JJL55gSYXF8e1N3DXbosSeJbNcP8",
	"aog69S6fML8idPEOBCYpl/O1nGjD9RlnEICoA4GwSG1hbgloXqbpChn0Diy0duXT90idVgFndzBnnTjk",
	"uqwJfAE4Ozn78DustqfvydkHdAWrzUlrNnir9sZp+sc8Ov7eTxMJ71cuefRyEtEyTfEsBS2YR/OKgXcM",
	"m1xpvDRX/IJv0DVOS+gu2FkgxVx85eCB6yPmAknMILEkvELiDeaolBMCSGye+VE4O3hcHy/qgYYFDWM2",
	"OfE9vf6GjS2VJERuiNOzBic2YXlPrwnLaQZUoGvMiESHT+R1odPytsvoeeI5shqM1DeP+OyKzAw4x4vQ",
	"QoPYMhvZVSRmgmTqnEDiF5JvkinPGMzJbRcK/bviLUQo0jPQNTAuNbghrZbROQuxs7PPeTn37qN/v+c+",
	"Rf8hxBILRCx2eGdJpBb0rKuu7UegC7H03Ej1ez+IFb1b1DMAN3eYeOjiw6Gk9UfCBSTnhnk7BMYpwZ6r",
	"cCJ/riA2RqtX1KYEqND27pB81GO9qxRlZXr0yZfKRFlPIqBBDYJulkDdS4tuSJoiuC0Ig9FaJIMsZ6tP",
	"b4eA+mTHqTkCJ1gMGmiGHp/s8LZPMoTKoDCaRFxg1qNdPbjBHJlJo3HDheSHcYc8V2M73tHQEe1oNGd5",
	"hm6WJF4iwhuQG3k/KAIbXpfr21Xc66LNYUeHCSzD2bPLu/XJ4ZDmcfSXtu6Qckst1WM0H/2PTwd8hpte",
	"k/m+ZmMLYWq5S71vWHSUIj/DJTcbz3GZiuh4jlMOHrcuz7B066QBWshJTUriuQCNKslxeelIiVmep4Cp",
	"vvKVRu/1fsywe95HiEvmQeq5+h3hNEV8xQVkKM6zrKTWZ70hYtm9n84pNrsGliy9UtgizSXE679MfNdf",
	"5Cgl1+BjTQ5xThN+0Mugh4MqyzmfYaE+Z2B3ZmHNtMbsamu6NI+luDg9++rZsMxmGunVOFS5vePstGqi",
	"EQvEIxdOMilXmttoEaNkA3k7bivJccTnqKvfLeJyFi+BC4aFz0y05vJv1vILIaQpbdFcjXd9HELFr2+8",
	"cNaRuyE2p9pK7SoavXkgMNEBEjhiJaWELlBO3YVHIJVX6ooJQhfDW5qB6Nzu3drHv4vAohwUYZKFz/VI",
	"aV1qI7cLzLem9dtP8PZ1sYFTA1EL15PmhfGyd5OFAhiswa/41l5S7XZ4/CYcLyF5W5I08XCmtGjlifUo",
	"pGLKHJGkRXEiIOOeYGqFF8wYXv2Utwl6sDp0kSq09rFv0+nwoPzp3wJ1mxuM2Ob2IFufV4drWQ7q9xaN",
	"gEqt+j1igBOp4xKGiUS7WpZSiIX+R0mXgFOxXEWXHsLW254uMV141N/mGG9hyiwgD/kFeJn1OZV7twwf",
	"2QCSONG3xeDkH0QsP4FgJOYvPvfT9bmzmkSj5Fq9BCOxV649Jyf+h/DHpTx64tEtoNftB68WPO5Dlgpw",
	"SuEkpzV9y9Di30ZqRrWiVeuEDjLhjpj5SfOZiz+Hl0Km6YvsDoqT58rmL3Helzhvf5zXHPD9LcRfTEJM",
	"VzCwRdOOGOV2Yup5wZX7lALPUmWsspIiQjlJYIgj4pvEuzHQ675H0BCg+eyfoFNTCC1KD5v9UejlEBcJ",
	"oaggBSQSYglmwXJ52XuClefa2JbLDgZnOk+aGnOXHlgbtNIpU11iwS0RpyZKOCYyVPlOnguSAGOhT8Yl",
	"8SSKBcD+mC88rnm+QEAFW+nYsqhyJDBNUEqovLnN86kfvevIL8jmGAWIoxYfyM2QNE4tXCPFSfu2VltN",
	"NMCXDTx4HKfU/No5Fu/Ky03seYn1zgVtQav2diD85GiAcekFdsagbG9sIh0N31KMxBsyhWs0hKJTG4a8",
	"46L8yiE5iwNJYyXHC0AFsBiowIuGLTFPc+ywIFUwGH18kQucegPo6ktvyDwQPMsgk6B6FzWvdTa1YPSa",
	"m1yWzCHZ/e+Lo7kcGjRO2USkw7nnVqd3o1PQ5c0qPqXtKclVWOUR+cJQF4Azj2pUqcQee9CkJtlIjJCz",
	"fZl6/J2N6bSX+McSxBLq6dZyMEGg1pJOwGj42SkEjfx9rGXjW6Fjs6jlqhwmgyz31JcGsy/5dMF8up8+",
	"Hc5wjzcls6JF1w7KjJPbMkDlzxaMUs7cOn/WzB4goO9EGjYNv/Gn/d44hPxx8Hnk4+1z9bA0qDGVVG46",
	"MpK35GQxTok6JRND2JRsjnip/Oh5meq3LyU/F+Raunt9kYctYgYDkqX2MRtnr921RxIvEk3nBb6hG4Ou",
	"ENwnF3YSPSjKWeoz65razIBFONLjUc5QTtOVSeUh0j+crTyaxlFzXGJhWx5u46HHENrK4/ehsyySLThO",
	"k01P3dK4ckMHdZmSP0Jg6OfeDxdyl6PbzNggSUPGuJJOvTh2xd0GkkIN9WrKyocyJtX3y07hj5IqauAm",
	"8pKPevZ0iG9NSwWrti1vMDHvnfY9VJeqXO4srLwtJ1Tvw5Uj2CBWOC5034DxFmI7yeMrYHOSeiyMd9U3",
	"x+4Ob7+NeFOkO8089sEX+QXFS4ivkAniIJEjUAEvsLHa6mrXb79BdlbhPO9eKgtlR7vs2OZ36OMy0lcl",
	"QYKctC+tIaHVoGyRtwc3SH6peGvD5D2bd0nE6lxylt7LeVU4KXWG/QwwA/abFfT6cP9vs1sVV6pDqWH1",
	"7kshCknQkyQjtLGgKtZcAk7UcFOu+X+v1MBXF82sWeOjyXXU/w2tcfbh1e8uDur552WBZ5jD6zGw2MFh",
	"cOyII0W5sas12MAutlZx33muRD8RUpRE74/eSoI6uS/H0eHB64NDuXdeAMUFiY6jXw4ODw5VoEAsFf2m",
	"mjyvFHk0L+fcFzLSOVEYUbhpJyxL3lNe64ckOo7Oci4cruCmmha4eJsnq53VUbbSrtdNrjXWZqMy92iH",
	"VbKeWklfyWynChISx0dIV07xrm+3CvypHFQXovaPlYPc26osdh83f7+UJrrA0ur4HjUZQd33JnNM7xo1",
	"7WvNJCn4Ilbv1O8I035e0cNcbjlplc27hfcBx6MeMm0W3cvTtTjgzcDTpz7P/YhkCqKHxr55FIIW5NUV",
	"rBQ2FiACuYY4TXXIzqgI3iHc30Fo+aqvdwPHm9VKj3oMcLRd9zGgW0ntEA8xECWjkHgO9ciXz6sTWiS0",
	"5JK2yAjB7J7PL5gdoj2ITHYp9SgiuQ1Ay1F1EPQkJfJmTOFe6emd7QsySjL384oRzJpbTup+IxuKYztx",
	"nCRuEOe5S+KNbzcWsadAVVv7Q+Q6k5N3TK3di4eO5zJKQhwOMIoJ7vwkjCJvvM42D6rw/1WftSvvU9z6",
	"ezQG0cbh1flJFX43w64i8pTmCYywOvQwD9CfzYfd2BrjItmqWG19eS+LQx9ob0ql7Ty3+Eh+NUykAJve",
	"6SKLdZAyfwehzoCUwxkizGdbqrGZxDEVHh7tsLt+O04x02jCVTUgT1KMjKNx0F5URSiIV5FfbMtdutbi",
	"zmj7AKZmu6pm3W3F5TcyDG0tBtSrmFriOaiQ8fe7UU/WL3RtPq5bXtW5524lZYsTArlU/yrBZu6IHM1J",
	"amO5dR3bf8HB4gD9GZUc2N/wLP6zPDw8+hUXxd8Klid/Rv99gN7jeKn0PKaJbsHDUVZygWaAvn75iIDG",
	"eQLJQTTR0TS1ax1Mq7KB+3q4Xe5Xr7RK8O6nYLrEU8x4OIYZD/eomJxo7PfL9eQe1lB90hFesc1TVhnM",
	"rReVrsBzmfyBHOSK7Pv1jhvbdiWim4gedot/EqZqiM+pU4i2oRjV6Z92fp9M/VSNeRGt9xKt4VLPXYvZ",
	"JnGfw/UYxe13VW1GbxTpd5KmtXQNhI8q9j536j02syLrSpGRIaSWLLsiafo8DLuH0o9Br67WjbMVUml9",
	"Yfn0QAQ83LV628bR43UrhJ+GLYJ3fgq3ELuvwD02UsUU7+WcDmPsrHfzA3mQnsqx8fHI3UNg6qG8nYh1",
	"noxJktmfYbYJi5uezENj//ro14GXWYbZqqrlk06CzUQytXy4re2jTW+RzeQLCl8rek0m3wjJ+1GP3Fr6",
	"TrxJWPKQwlM8xnW/Tb7MyzSR9mAlMglFGUlTYhpyBGxDlfvVMAw7qar9bcs6pi++laMRrTJj+6AMQJWS",
	"jDShqjuSHB4ebtpaZA8KTVF9G3WmOetFp8nbOOTBuRdyjLdW3cmg27Y/o2gXvVG2Ya+G4/PTc1hhOyr5",
	"o1Gq4VKreG+MYaUbNe3bZ9JFhA0rQ0UIYky1jFUdpl6MiY25hMGcAV9CT5rlFz2kcdXgVgBNVMMMwU29",
	"nG6UNZKNvlT73peVtrPCm9nJSakB9qSmmC8qQ1l3m3DxUKv5KygEwqpVWN0aTJXY3Wpt/cuvUpsPNEZt",
	"FfqPfD9qiUaN2T15kk+Ag+Xd72Nf+X0LSacnPhJ/9gYUm/30nm7U3ojlvYW6flAZ7XQr9LP4OQi35WG7",
	"V+EBuvD3akK3VlA5b1GkLik2zHuATnGaKrdsSbg0s5Z5grIyFaRIwZQD5tfAbhgRpjLw4uLjBAGOdasJ",
	"VHI9HVBcMgZUuB0oTPce6/sVOZHfc5QB5iWDxtGspD4YeYkvqi6Qj69lGl0n26WK8nC14qjp4eLL1B4F",
	"1VC3A9c2/bgNlJc70UbcsKaF1K7+s9noAnA2MsPd6+hdmA/7fLhSlT73fKPSB9rf81K79KuPjI00Ffmb",
	"JZV+jR9FLjvUS7L6oy8O3QoEVZ093EjQVtWDl/tmE5O9cG9Wsfh6+uxSwzq6CqInxcPllIcwGL2lx6PM",
	"xqOdwxCyG3VvCmk14jiGQlhv/sk9YO+CZRpiZnpX15CPLZMIMJMeUbHThVubvpn945S1j4/YNJos7KJY",
	"4vFvdm8FRPhSy2kPQoaHEw7NcvKtyyA6XUGCpRA/5M2eBKMQWsBhOlIVPA+meY4a5QfQElP9V0ymd6bh",
	"yLonNqD6WrjtKkYxnf4jFm+rfibbc+BkcLTtmuJRNEd+CaNJu3Q6FP+wlJ3WfXKCD4WVwNV4CZXFDJH5",
	"3Pas2QuxO8/pH2gCt1VHSRsNmtnuQsHXf93QtNW2zffSni/4H/M5h8Bz+5N6a2+2dtroObRCw9OMsezq",
	"/lwfbVJP0ltH8u3oR64k6Vy03zSwNaCzFcopoJyhLGe6CklhAm6LVLW9Nn+LJ5BVo27cds//dRP4Tnew",
	"leohI2+kR1acloznTGKeV/otlbSeszwLIIvCrbhwO/6Mw1Y3y0cdUPVaV9cOFcBQodsV7yjDx74Z6u99",
	"fyL/pU7o+ZZ0qH3YtRU0JUtNyyl+PJ3ighzA0ewAF0XkrHBXhwvraNldK5m1+aMKbbr/bvRgcT/Yku71",
	"5frfAQAA//8DK9yLbYYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
