// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaSXMbuRX+Kygkx7ZJzyg5MCeJcs2oPLJcksZJlYoHsPuRjVE30IOFFkvF/556AHpv",
	"kq3RMktyMkU+vPXD2+BHGsu8kAKE0XT2SBXoQgoN7o+T6RT/iaUwIAx+ZEWR8ZgZLsXkFy0FfqfjFHKG",
	"n/6uYEVn9G+TmufE/6onH5WSiu52u4gmoGPFC2RCZ/SMJUTBrxa0obuInkw/vL7MU2tSECZwJeDpUPjJ",
	"6wv/LA1ZSSsSlPiPt3DxDagNqNLMXRT4uRjPM6sNqM8yAfyzULIAZbgHgJAJXJzjp64JCZCLcxpRsy2A",
	"zqg2ios1GqRBbXgMP0pt9pwrFN8wAySV2hCWJAq0JkwkJBwlhVTmAOsLoQ0T8aBiN4EFDzSHlbwxTBlI",
	"Tgc0veU5kG8pCGJSIOgH8o1pomDN0V2Q0IiupMqZoTOaMAPvDM/hsCxj9bEQNqIRDtQcbh3n0ecdeX36",
	"KyjNPZraloYfiFw5UwP5AUvCgbnMcz7guRtpVQwkRpdtRvLeRRRTAEe/zu5K2A1FvGfPHrUGYtx2ZDcw",
	"beQudlHzZlyIlXzJ2zEGwseRa4tRuNXeA28P2DeD3Nc/CMxs0YNVB0i1UztBN5gRg/6xp3fRoxEFYXNU",
	"NwWWmXRLI5ooxgVaFFEryq8XA+7rpoOe3HlDFDH+XpTypIpT0EYxIxV+nazhkJCrBvlwNcnBKB6fc31/",
	"efazxhh01TnNpRUG/ZBwfU90wTCTWKVAmGxLrIaEcEEuz5pg5sL886QONhcG1uDKuRd4zfLj8q5PL58t",
	"6IaJZCkfQF9b4cLzNvZ9nRd22LzPNl+CQnGb+ZefdUMSFyhsnJTfkOaUzHzIuYF8bA5pAuhaZq54Bc5M",
	"Kbb9f3fxuyTr0ug6E/7WxuAYo7ftAhyG+l2Ah27vbvWTSdTPZ3sTwWI4TTqU93MyK9iSZ9xsy4LQzcTD",
	"CdpAXmSIlaXlWQJqMFn7GaGXmuOQsNuaOGLXyXUyxfff7clHWrP1PkZHAx4ElVzQacGTcwXMwJwZlsn1",
	"dRgWe0bAA8QWJV64XNizvemvi4F02QwN3k4Fvp3wOhCuSZGx2MW5fwU80R7J4ddL9vATiLVJ+7Iv2QPP",
	"bU4Sq/xMygVJpVV6XI4OAhzMMbkcywRIow3Li14QOk6KWl5t2jlg1YAeNQbl8heI3YgfgnoOGTw/qIcc",
	"3zFtnyUHdPz4APFe1Vgcg9a38h4G0ubVBpTiCRBPRQyS+QrvEj9O/Cw2XKwJiM0gpphaD7SKV+4DywhT",
	"a5tjVEnBNPI10rePMs+ZQI5V9e2x7tbV8kz/5jqfsWUGyF5ZBKZGs/YpHX8b4PJvqe7R0oQriI1UW7KS",
	"yilbKInuGeIEYuO8nCTcW/yl5f0efUdxseFKCnQQ2TDF0QRNuMAAuy4reKunQI2BDvS6jik8pzI9VNSE",
	"JyAMX3FQ/yI51zkzcUrYUiqjnchy2zVgM5Z5ac0NxFIkh4IfCInbFtWxRyUa/I/m7F4G9jA4eiP8knDo",
	"tnIzH6wlX7yfCVI8oaToAwOT1cTAgyEKjFUCErLc7oWlNgkoNVhsjVUYRsNEwlQStmTDLKQ1Y1hIawpr",
	"Butdz623oWqfYdH+Sa71fudmsswHK2YzQ2d3i94yFbkQRzj++ndA4E5j8a2LxOxxVDvqWsHYKm62N1ho",
	"vNqnBf8E21Pryx5HNVNg2KBEVDCsVfQ/706/XLz7BNuaJ3On/DaTh/WL4QYbJvrxuzPyEcfRiG7KtpVO",
	"3394P3VlvgDBCk5n9Pv30/dTGtGCmdSpMvHDMn5cw0Aof3Q/kziF+J46Tr4aYwIIP87Db61F+Xd+i9tm",
	"FuqG6+y1dVVgZTO0aBeVmkxyFqdcwCiNXNIMB4guG9a9Sl4G1i+mq1FsteLxeF3DAcyxD9tDqt4Gzs9X",
	"dfNhUqJlUEeETTUKIiWi2k8Qbe2+fnBLv2GNXmRd390vDi3uK/uybZ3m3LzY1L1+NhmSVxkwQaL6zeEw",
	"LRLVPtXlRDOJfb/mPYsNHH7quq5s2z2tb/SozzKgzZlMti/mxUPN5K6d2oyysBsDsZbbvZVJaxQITiAg",
	"jNp690/HuH/6iqGqcy+d3bWz7t1it4iotnnO1JbOqHcWYXvsiahhWGnuaBV2Vw+KsHU5HG0/q71utAfn",
	"wReJduw4/6Wi7Z31xGj37v1jOS+d7ybYZbr25DAgsFV01VexHAwo7VRtO/+i6pWr7b0/jP0LEmDtrhuF",
	"SgnaDXXUQFC3LVm8KhibM+J4DL68BqFtHCgjc9/W42RY+GSmG5h/TUSHB/VjtCevh34/wCL8w3BTDrCs",
	"gbRDN8D3Cu8SrmO5AbWdYPnVexuMH8A0H6FIde5ItxG2o+cl+Wcn5ZnYqSYAlmVXK+erkR0J3S36c8LI",
	"/oRlWesNS/+eebAKbTeOR0M8aa7CmgE/FrofwFy1jr5UFJ/4iOLj+Jwotj3wh6hm5f2SHQ8/I86P/qVh",
	"N3Hvqs3C1t3RqnvffDNNGm+wY67yuWN9pBjWL2oDpa96Dnli3XtS++P+rwBWYmdmZeNfsEK8BF7ueZbt",
	"h8snnmXV+95ImOCZPxtKnBf+NxFSPrnpiXtz05NH9y9io1zW7akZvbVfP+oD0Q3cnxTeKHD61YLr9gOr",
	"1jvPi3AsnfF0bp2RQCTwUE0DCDUu1mRZbjaJSZkhOpU2S8gS6oL1jZvUnSkVKW9I1/LVSoN7+q10qjaq",
	"04GldM4Fz23ufuztzxev2N3vXw2PLuJNd9Qu1H++IfZ2wIj6ilb3EK/mrvr+sRobe1cYYdeeKbFNXez+",
	"GwAA///6Irc/EC0AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
