// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"time"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for ClusterNodeStatus.
const (
	Draining  ClusterNodeStatus = "draining"
	Healthy   ClusterNodeStatus = "healthy"
	Unhealthy ClusterNodeStatus = "unhealthy"
)

// Defines values for ClusterNodeType.
const (
	ClusterNodeTypeEdge         ClusterNodeType = "edge"
	ClusterNodeTypeOrchestrator ClusterNodeType = "orchestrator"
)

// Defines values for ClusterOrchestratorRole.
const (
	ClusterOrchestratorRoleOrchestrator    ClusterOrchestratorRole = "orchestrator"
	ClusterOrchestratorRoleTemplateBuilder ClusterOrchestratorRole = "template-builder"
)

// ClusterNode defines model for ClusterNode.
type ClusterNode struct {
	// NodeID Node ID
	NodeID string `json:"nodeID"`

	// ServiceHost Node private host address and service port
	ServiceHost string `json:"serviceHost"`

	// ServiceInstanceID Service instance ID
	ServiceInstanceID string `json:"serviceInstanceID"`

	// ServiceStartedAt Time when the node was registered
	ServiceStartedAt time.Time `json:"serviceStartedAt"`

	// ServiceStatus State of the cluster node
	ServiceStatus ClusterNodeStatus `json:"serviceStatus"`

	// ServiceType Cluster node type
	ServiceType ClusterNodeType `json:"serviceType"`

	// ServiceVersion Version of the service
	ServiceVersion string `json:"serviceVersion"`

	// ServiceVersionCommit Source code version of the service
	ServiceVersionCommit string `json:"serviceVersionCommit"`
}

// ClusterNodeInfo defines model for ClusterNodeInfo.
type ClusterNodeInfo struct {
	// NodeID Node ID
	NodeID string `json:"nodeID"`

	// ServiceInstanceID Service ID
	ServiceInstanceID string `json:"serviceInstanceID"`

	// ServiceStartup Time when the node started
	ServiceStartup time.Time `json:"serviceStartup"`

	// ServiceStatus State of the cluster node
	ServiceStatus ClusterNodeStatus `json:"serviceStatus"`

	// ServiceVersion Version of the service
	ServiceVersion string `json:"serviceVersion"`

	// ServiceVersionCommit Version of the service
	ServiceVersionCommit string `json:"serviceVersionCommit"`
}

// ClusterNodeStatus State of the cluster node
type ClusterNodeStatus string

// ClusterNodeType Cluster node type
type ClusterNodeType string

// ClusterOrchestratorNode defines model for ClusterOrchestratorNode.
type ClusterOrchestratorNode struct {
	// MetricDiskMBUsed Amount of disk space currently used in MB
	MetricDiskMBUsed int64 `json:"metricDiskMBUsed"`

	// MetricRamMBUsed Amount of RAM currently used in MB
	MetricRamMBUsed int64 `json:"metricRamMBUsed"`

	// MetricSandboxesRunning Amount of disk space currently used in MB
	MetricSandboxesRunning int64 `json:"metricSandboxesRunning"`

	// MetricVCpuUsed Number of vCPUs currently in use
	MetricVCpuUsed int64 `json:"metricVCpuUsed"`

	// NodeID Node ID
	NodeID string                    `json:"nodeID"`
	Roles  []ClusterOrchestratorRole `json:"roles"`

	// ServiceHost Node private host address and service port
	ServiceHost string `json:"serviceHost"`

	// ServiceInstanceID Service instance ID
	ServiceInstanceID string `json:"serviceInstanceID"`

	// ServiceStartedAt Time when the node was registered
	ServiceStartedAt time.Time `json:"serviceStartedAt"`

	// ServiceStatus State of the cluster node
	ServiceStatus ClusterNodeStatus `json:"serviceStatus"`

	// ServiceVersion Service Version
	ServiceVersion string `json:"serviceVersion"`

	// ServiceVersionCommit Service Version
	ServiceVersionCommit string `json:"serviceVersionCommit"`
}

// ClusterOrchestratorRole Capability of the orchestrator
type ClusterOrchestratorRole string

// Error defines model for Error.
type Error struct {
	// Code Error code
	Code int32 `json:"code"`

	// Message Error
	Message string `json:"message"`
}

// SandboxCreateCatalogRequest defines model for SandboxCreateCatalogRequest.
type SandboxCreateCatalogRequest struct {
	ExecutionId string `json:"executionId"`

	// OrchestratorId Orchestrator where the sandbox is placed
	OrchestratorId string `json:"orchestratorId"`
	SandboxId      string `json:"sandboxId"`

	// SandboxMaxLength Maximum duration in hours
	SandboxMaxLength int64     `json:"sandboxMaxLength"`
	SandboxStartTime Timestamp `json:"sandboxStartTime"`
}

// SandboxDeleteCatalogRequest defines model for SandboxDeleteCatalogRequest.
type SandboxDeleteCatalogRequest struct {
	ExecutionId string `json:"executionId"`
	SandboxId   string `json:"sandboxId"`
}

// SandboxExecRequest defines model for SandboxExecRequest.
type SandboxExecRequest struct {
	// AccessToken Override access token used when contacting envd
	AccessToken *string `json:"accessToken,omitempty"`

	// Args Optional arguments passed to the command
	Args *[]string `json:"args,omitempty"`

	// Command Executable to run inside envd
	Command string `json:"command"`

	// Cwd Working directory for the process
	Cwd *string `json:"cwd,omitempty"`

	// Env Environment variables injected into the process
	Env *map[string]string `json:"env,omitempty"`

	// ExecutionId Expected sandbox execution identifier; mismatch aborts the request
	ExecutionId *string `json:"executionId,omitempty"`

	// TimeoutSeconds Optional timeout applied to the exec request
	TimeoutSeconds *int32 `json:"timeoutSeconds,omitempty"`
}

// SandboxExecResponse defines model for SandboxExecResponse.
type SandboxExecResponse struct {
	// ExitCode Process exit code
	ExitCode *int32 `json:"exitCode,omitempty"`

	// Status Status text returned by envd
	Status *string `json:"status,omitempty"`

	// Stderr Captured standard error
	Stderr *string `json:"stderr,omitempty"`

	// Stdout Captured standard output
	Stdout *string `json:"stdout,omitempty"`
}

// TemplateBuildLogsResponse defines model for TemplateBuildLogsResponse.
type TemplateBuildLogsResponse struct {
	// Logs Build logs
	Logs []string `json:"logs"`
}

// Timestamp defines model for Timestamp.
type Timestamp = time.Time

// N400 defines model for 400.
type N400 = Error

// N401 defines model for 401.
type N401 = Error

// N404 defines model for 404.
type N404 = Error

// N500 defines model for 500.
type N500 = Error

// V1TemplateBuildLogsParams defines parameters for V1TemplateBuildLogs.
type V1TemplateBuildLogsParams struct {
	OrchestratorID string `form:"orchestratorID" json:"orchestratorID"`
	TemplateID     string `form:"templateID" json:"templateID"`

	// Offset Index of the starting build log that should be returned with the template
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// V1SandboxCatalogDeleteJSONRequestBody defines body for V1SandboxCatalogDelete for application/json ContentType.
type V1SandboxCatalogDeleteJSONRequestBody = SandboxDeleteCatalogRequest

// V1SandboxCatalogCreateJSONRequestBody defines body for V1SandboxCatalogCreate for application/json ContentType.
type V1SandboxCatalogCreateJSONRequestBody = SandboxCreateCatalogRequest

// V1SandboxExecJSONRequestBody defines body for V1SandboxExec for application/json ContentType.
type V1SandboxExecJSONRequestBody = SandboxExecRequest
